### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by adamskoruba** [TIS2024-FMFI/students#1]
Vytvorenie katalógu požiadaviek

**Comment by adamskoruba** [comment]
treba vytvoriť shared dokument kde to budeme editovať

**Comment by Hedgeh0g1** [comment]
https://drive.google.com/drive/folders/1I9x06j-7bMtQXQAgAq_TeWaIJqGRvNyy
Vytvoril som goodle drive na to

**Comment by Hedgeh0g1** [comment]
Pridal som abstraktnu štruktúru aplikacie na Google Drive

**Comment by Hedgeh0g1** [comment]
Pozrieť Memgraph ako jednu z možných technológii na ktorú budeme prerábať existujúci databázu

**Comment by pavelpetrovic** [comment]
tu su moje pripomienky ku KP:

 - definicie patria do 1. casti - slovnik pojmov
 - odkazy zasa patria do odkazov
 - 2.2 ma byt sloh o tom, co system bude robit, nie do uplnych podrobnosti, ale zasa nevynechat nic podstatne. Cele vety.
 - 3. cast obsahuje tiez iba cele vety. Vsetky myslienky su atomicke a ocislovane.

**Comment by adamskoruba** [comment]
link na updatnuty katalog - https://docs.google.com/document/d/1zI4p9-4sDI28uh53AOb7NC1Vs9D47d9eN_gvJ3GIUrA

**Comment by pavelpetrovic** [comment]
- po spusteni aplikacie pouzivate prihlasi skratkou fakulty a heslo, resp. rektoratnym uctom a heslom
- 3.2.1.a sa mi zda, ze je jednoduchsie downloadnut zo servra cely ZIP fakulty lokalne to nacitat a na servri nemat ziaden vlastny softver, iba tam pristupovat cez scp/sftp
- 3.2.3. "vypisovať údaje " - nie je jasne, co to znamena, treba to presne zapisat
- 3.2.1.2. filtrovanie - preco je to v importe dat?
- 3.3. nehovori nic, cele dat prec
- 3.4. prihlasovanie by tam snad vobec nemuselo byt a heslo sa pouzije pri zavolani scp datovych suborov zo servra

cele poprehadzovat a krajsie rozpisat co system ponuka pouzivatelovi

**Comment by adamskoruba** [comment]
18.11. - upravene na trochu aktualnejsiu verziu, pridane/odobrane dane veci
