### ISSUE TITLE
UML class diagram

### ISSUE THREAD

**Issue by adamskoruba** [TIS2024-FMFI/students#14]
UML class diagram

**Comment by Fifoval** [comment]
![UML-CLASS-V1](https://github.com/user-attachments/assets/c98041c3-7944-42bd-aa99-9f150c4ca2f9)

**Comment by Fifoval** [comment]
![UMLClass2 drawio](https://github.com/user-attachments/assets/0994554e-b543-4931-a216-65f7f51e5733)

**Comment by Fifoval** [comment]
![UMLClass3(1)](https://github.com/user-attachments/assets/2c19ac60-1934-4972-bc32-a9907d833dd4)

Update UML Class diagramu
