### ISSUE TITLE
testovacie scenare

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2024-FMFI/students#19]

**Comment by adamskoruba** [comment]
- akcia: prihlásenia používateľa do aplikácie (vyplnenie prihlasovacieho formulára)
- reakcia: prechod na ďalšiu scénu s loading barom a spustenie sťahovania súborov
- požiadavka: 

- akcia: chybné prihlásenie používateľa do aplikácie (zadanie nesprávnych údajov)
- reakcia: zobrazenie chybového hlásenia "nesprávne meno/heslo" pod prihlasovacím formulárom
- požiadavka:

- akcia: sťahovanie dát po správnom prihlásení
- reakcia: prechod do hlavnej scény (kde je filter, export atď)
- požiadavka:

- akcia: zadanie mena/priezviska, rodného čísla, akademického roka do filtračného formulára a kliknutie tlačidla "Hľadaj"
- reakcia: zobrazenie konkrétnych študentov (štúdii), ktorí spadajú do filtra
- požiadavka:

- akcia: kliknutie na tlačidlo "export {názov}" (pre všetky 3)
- reakcia: otvorenie dialógového okna s lokálnymi súbormi, kde užívateľ zvolí kam chce stiahnuť súbor
- požiadavka:

- akcia: kliknutie na tlačidlo - reset (v hlavnej sekcii)
- reakcia: vynulovanie výsledkového okna a možnosť zadať nové údaje do filtra
- požiadavka:

- akcia: kliknutie na konkrétneho študenta (jeho štúdium) vo výsledkovom okne a stlačenie tlačidla ✓
- reakcia: vyplnenie údajov v sekcii o detailoch študenta (pravá časť scény)
- požiadavka:

- DOPLNIŤ ĎALŠIE!

**Comment by adamskoruba** [comment]
- **Akcia:** prihlásenia používateľa do aplikácie so správnymi prihlasovacími údajmi (vyplnenie prihlasovacieho formulára)
- **Reakcia:** prechod na ďalšiu scénu s loading barom a spustenie sťahovania súborov
- **Požiadavka:** 3.2.1
- #23  #29 
<br/>

- **Akcia:** chybné prihlásenie používateľa do aplikácie (zadanie nesprávnych údajov)
- **Reakcia:** zobrazenie chybového hlásenia "nesprávne meno/heslo" pod prihlasovacím formulárom
-  **Požiadavka:** 3.2.1
- #23 
<br/>

- **Akcia:** sťahovanie dát po správnom prihlásení
- **Reakcia:** prechod do hlavnej scény (kde je filter, export atď)
-  **Požiadavka:** 3.3.1.1
- #26 #27 
<br/>

- **Akcia:** zadanie mena, priezviska, rodného priezviska, dátumu narodenia, miesta narodenia do vyhľadávacieho formulára a kliknutie tlačidla "Hľadaj"
- **Reakcia:** zobrazenie konkrétnych štúdií, ktoré spadajú do filtra
-  **Požiadavka:** 3.3.2.
- #30 #28 
<br/>

- **Akcia:** kliknutie na tlačidlo "export {názov}" (pre všetky 3)
- **Reakcia:** otvorenie dialógového okna s lokálnymi súbormi, kde užívateľ zvolí kam chce stiahnuť súbor
-  **Požiadavka:** 3.3.3
- #31 
<br/>

- **Akcia:** kliknutie na tlačidlo - reset (v hlavnej sekcii)
- **Reakcia:** vynulovanie výsledkového okna a možnosť zadať nové údaje do vyhľadávacieho formulára
-  **Požiadavka:** 3.3.2.13
- #28 
<br/>

- **Akcia:** kliknutie na konkrétneho študenta (jeho štúdium) vo výsledkovom okne a stlačenie tlačidla Zobraz
- **Reakcia:** vyplnenie údajov v sekcii o detailoch študenta (pravá časť scény)
-  **Požiadavka:** 3.3.2.9
- #28 
<br/>

- **Akcia:** Stiahnutie dát v download scéne (stiahnutie zo servera)
- **Reakcia:** načítanie dát do pamäte a vymazanie všetkých temp súborov
-  **Požiadavka:** 3.3.1
- #27 
<br/>
