### ISSUE TITLE
Ukazka vystupnych dokumentov

### ISSUE THREAD

**Issue by adamskoruba** [TIS2024-FMFI/students#3]
Buduci tyzden (pondelok 21.10.) by sme mali vidiet ukazku dokumentov (pre soc. poist, diplom atd)

**Comment by adamskoruba** [comment]
tak az 29.10.

**Comment by Fifoval** [comment]
![IMG_7507](https://github.com/user-attachments/assets/9ac46a21-1f54-477c-a22d-5c4432e202ef)
![IMG_7476](https://github.com/user-attachments/assets/614f1103-1c6b-4788-977b-f381f3f9e7ea)
![IMG_7477](https://github.com/user-attachments/assets/ae881960-f609-4b3d-8c0e-d5a224cfb77e)
![IMG_7478](https://github.com/user-attachments/assets/986b1a28-5217-4231-b030-273ce5370947)

**Comment by Fifoval** [comment]
![IMG_7507](https://github.com/user-attachments/assets/97a42ab3-5eb3-4a1f-8b0f-a928c513bd1a)
![IMG_7476](https://github.com/user-attachments/assets/3394c226-1028-4d0e-8016-05a43eca4eb0)
![IMG_7477](https://github.com/user-attachments/assets/37288540-32ee-4782-8c44-a7fa01c74d6f)
![IMG_7478](https://github.com/user-attachments/assets/b3e930e0-04eb-4178-a5f7-a8e49a025326)

**Comment by Fifoval** [comment]
Hromadná korešpondencia Word, predpripravená štruktúra dodatku k diplomu
[DkD.docx](https://github.com/user-attachments/files/17935122/DkD.docx)

**Comment by adamskoruba** [comment]
![soc_poist_ais](https://github.com/user-attachments/assets/c75173ea-e600-41d3-b99e-fb6970fd2952)
![vypis](https://github.com/user-attachments/assets/d18e6f37-74d7-4e69-9567-ea50990c617f)
