### ISSUE TITLE
Odovzdaný katalóg požiadaviek.

### ISSUE THREAD

**Issue by Fifoval** [TIS2024-FMFI/students#4]
Po 2.stretnuti so zadávateľom (14.10.) sme odovzdali katalóg požiadaviek na kontrolu. Čakáme či treba niečo pozmeniť/pridat.

**Comment by adamskoruba** [comment]
link na katalog - https://docs.google.com/document/d/1zI4p9-4sDI28uh53AOb7NC1Vs9D47d9eN_gvJ3GIUrA
