### ISSUE TITLE
prezistit CIT informacie

### ISSUE THREAD

**Issue by adamskoruba** [TIS2024-FMFI/students#5]
Prezistit ake moznosti nam ponuknu z citu, server atd.
Idealne cez p. Petrika

**Comment by pavelpetrovic** [comment]
aktualne:

vsetci pritomni
pracuje sa na navrhu pouzivatelskeho rozhrania
na formate XML suborov a schemy XSD
treba uz naozaj ziskat kopie vystupnych tlaciv
KP potrebujeme este poriadnejsie zapisat podrobnejsie rozpisat, logickejsie clenit
jeden modul samostatny nezavisly bude konvertovat CSV do XML
