### ISSUE TITLE
gui mockup

### ISSUE THREAD

**Issue by adamskoruba** [TIS2024-FMFI/students#7]
treba vytvorit gui mockup +- ako bude aplikacia vyzerat

**Comment by Fifoval** [comment]
![IMG_7401](https://github.com/user-attachments/assets/b9e70034-fe59-49c4-a7ce-049cf32d6206)

**Comment by adamskoruba** [comment]
+ este dalsia "podstranka" loading bar

**Comment by adamskoruba** [comment]
![tis_login](https://github.com/user-attachments/assets/f6f1862c-49d3-4d87-b9ce-dbbd53f98aae)

**Comment by adamskoruba** [comment]
![mockup](https://github.com/user-attachments/assets/0d7070b9-2f37-48a6-a801-2767702e1f62)

**Comment by adamskoruba** [comment]
![loading_scene](https://github.com/user-attachments/assets/622a04d6-2b63-45ff-883f-db460bb2a863)
![main_scene](https://github.com/user-attachments/assets/356a8bd6-f330-4af6-8e50-55d712048480)
